version: '2'
services:

  front-envoy:
    build:
      context: .
      # Build a container using the Dockerfile-frontenvoy file located in the current directory
      dockerfile: Dockerfile-frontenvoy
    volumes:
      # Mount the front-envoy.yaml file in this directory as /etc/front-envoy.yaml
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      # Create and use a Docker network named “envoymesh” for this container
      - envoymesh
    expose:
      # Expose ports 80 (for general traffic) and 8001 (for the admin server)
      - "80"
      - "8001"
    ports:
      # Map the host port 8000 to container port 80, and the host port 8001 to container port 8001
      - "8000:80"
      - "8001:8001"

  service_blue:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service_blue
    environment:
      - SERVICE_NAME=blue
    expose:
      - "80"
  service_green:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service_green
    environment:
      - SERVICE_NAME=green
    expose:
      - "80"
  service_red:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service_red
    environment:
      - SERVICE_NAME=red
    expose:
      - "80"

networks:
  envoymesh: {}
